import Head from "next/head";
import { Footer, Hero, Latest, Navbar, Popular, Subscribe, Testimonial } from "@/components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gramedia</title>
        <meta name="description" content="Generated By Radit"/>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>
        <link rel="icon" href="favicon"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.google.com/specimen/Quicksand?query=quicksand" rel="stylesheet"/>
      </Head>
    <main className="bg-white">
      <div className="px-10">
      <Navbar/>
      <Popular/>
      <Latest/>
      <Subscribe/>
      <Testimonial/>
      </div>
      <Footer/>
    </main>
    </div>
  );
}
